"""
Django settings for ivod_platform project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from sys import stderr
import datetime
import importlib.util

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = (os.environ.get('DEBUG', 'False').upper() == 'TRUE')
SECRET_KEY = os.environ.get('SECRET_KEY')
ADMIN_PASS = os.environ.get('ADMIN_PASS')


if 'ALLOWED_HOSTS' in os.environ:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'django.contrib.staticfiles',
    'corsheaders',
    'platformAPI',
    'rest_framework',
    'django_filters',
    'rest_framework_jwt',
    'rest_framework_jwt.blacklist',
    #'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'platformAPI.middleware.TokenCopierMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        #'rest_framework_simplejwt.authentication.JWTAuthentication'
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_AUTH_COOKIE': "JWT-Cookie",
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_DELETE_STALE_BLACKLISTED_TOKENS': True
}

ROOT_URLCONF = 'ivod_platform.urls'

#TODO: Manage load order of templates if specific cases occurr.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR).resolve().joinpath('platformAPI').joinpath('templates'), Path(BASE_DIR).resolve().joinpath('platformFrontend').joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ivod_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = ['platformAPI.backends.EmailAuthBackend']
AUTH_USER_MODEL = "platformAPI.User"


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     str(BASE_DIR.joinpath('static'))
# ]


DATASET_BASE_URL = "./"
CHART_BASE_PATH = str(BASE_DIR.joinpath("chart_data"))
DATASOURCE_BASE_PATH = str(BASE_DIR.joinpath("datasources"))
JS_BASE_PATH = str(BASE_DIR.joinpath("code"))
#CHART_TEMPLATE = "/Path/To/Template/File"

PASSWORD_RESET_URL = os.environ.get("PASSWORD_RESET_PATH", None)


#CORS Config
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost').split(',')

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DATA_ALLOW_UNORDERED = False


if 'CUSTOM_SETTING_PATH' in os.environ and Path(os.environ.get('CUSTOM_SETTING_PATH')).exists():
    #Import custom settings into namespace
    spec = importlib.util.spec_from_file_location("costume_settings_module.settings", os.environ.get('CUSTOM_SETTING_PATH'))
    foo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(foo)
    globals().update({ key:foo.__dict__[key] for key in foo.__dict__.keys() if not key.startswith("_")})


# Verification steps
# Check if all required values are set
# If DEBUG=True unset values may be overridden by defaults.
# If a value is overridden, a warning should be printed to stderr
# Otherwise an error must be raised

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'NOT_SAFE_FOR_PRODUCTION'
        print(f'----------------\nWARNING: No secret key set.\nTHIS WILL FAIL WITHOUT DEBUG!\nSecret key defaulted to {SECRET_KEY}\n----------------', file=stderr)
    else:
        raise ValueError("No secret key set. Use environment variable SECRET_KEY!")

if not ADMIN_PASS:
    if DEBUG:
        ADMIN_PASS = 'NOT_SAFE_FOR_PRODUCTION'
        print(
            f'----------------\nWARNING: No admin password set.\nTHIS WILL FAIL WITHOUT DEBUG!\nAdmin password defaulted to {SECRET_KEY}\n----------------',
            file=stderr)
    else:
        raise ValueError("No admin password set. Use environment variable ADMIN_PASS!")