# Generated by Django 3.1.3 on 2020-11-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='auth_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='charts_shared_with_group',
            field=models.ManyToManyField(blank=True, to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='datasources_shared_with_group',
            field=models.ManyToManyField(blank=True, to='platformAPI.Datasource'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='charts_shared_with_user',
            field=models.ManyToManyField(blank=True, to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='datasources_shared_with_user',
            field=models.ManyToManyField(blank=True, to='platformAPI.Datasource'),
        ),
    ]
