# Generated by Django 3.1.3 on 2020-11-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformAPI', '0003_auto_20201112_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='original_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='platformAPI.datasource'),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='charts_shared_with_group',
            field=models.ManyToManyField(blank=True, null=True, to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='datasources_shared_with_group',
            field=models.ManyToManyField(blank=True, null=True, to='platformAPI.Datasource'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='charts_shared_with_user',
            field=models.ManyToManyField(blank=True, null=True, to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='datasources_shared_with_user',
            field=models.ManyToManyField(blank=True, null=True, to='platformAPI.Datasource'),
        ),
    ]
