# Generated by Django 3.1.3 on 2020-11-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformAPI', '0004_auto_20201112_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancedgroup',
            name='charts_shared_with_group',
            field=models.ManyToManyField(to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhancedgroup',
            name='datasources_shared_with_group',
            field=models.ManyToManyField(to='platformAPI.Datasource'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='charts_shared_with_user',
            field=models.ManyToManyField(to='platformAPI.Chart'),
        ),
        migrations.AlterField(
            model_name='enhanceduser',
            name='datasources_shared_with_user',
            field=models.ManyToManyField(to='platformAPI.Datasource'),
        ),
    ]
