# Generated by Django 3.1.3 on 2020-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformAPI', '0005_auto_20201117_0652'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(fields=('owner', 'scope_path'), name='chart_unique_user_scope_path'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('owner', 'scope_path'), name='datasource_unique_user_scope_path'),
        ),
    ]
