# Generated by Django 3.1.3 on 2020-11-26 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformAPI', '0007_auto_20201119_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhancedgroup',
            name='charts_shared_with_group',
        ),
        migrations.RemoveField(
            model_name='enhancedgroup',
            name='datasources_shared_with_group',
        ),
        migrations.RemoveField(
            model_name='enhanceduser',
            name='charts_shared_with_user',
        ),
        migrations.RemoveField(
            model_name='enhanceduser',
            name='datasources_shared_with_user',
        ),
        migrations.AddField(
            model_name='chart',
            name='shared_groups',
            field=models.ManyToManyField(related_name='chart_shared_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='chart',
            name='shared_users',
            field=models.ManyToManyField(related_name='chart_shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='shared_groups',
            field=models.ManyToManyField(related_name='datasource_shared_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='shared_users',
            field=models.ManyToManyField(related_name='datasource_shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasource_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
