# Generated by Django 3.1.3 on 2020-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformAPI', '0008_auto_20201126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='config',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
